version: 0.2

phases:
  install:
    commands:
    - rm package-lock.json
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless
    - npm --version
  pre_build:
    commands:
    - npm install --silent --no-progress
  build:
    commands:
    - npm run-script lint
    - npm run test
    - mkdir -p stg
    - serverless package --package stg --stage stg -v -r eu-central-1

artifacts:
  files:
  - target/**/*
  - serverless.yml
  - deploy.sh
